openapi: 3.0.0
info:
  title: Nepal Commerce API
  description: Ecommerce Multi-Vendor
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: user
  - name: vendor
  - name: Brand
  - name: Category
  - name: Attribute
paths:
  /api/user/register:
    post:
      tags:
        - user
      summary: user register
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  example: customer
                email:
                  type: string
                  example: customer@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
                password_confirmation:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/login:
    post:
      tags:
        - user
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: vendor@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: password
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /vendor/user/register:
    post:
      tags:
        - vendor
      summary: vendor registration
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: vendor
                email:
                  type: string
                  example: vendor@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
                password_confirmation:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /vendor/user/login:
    post:
      tags:
        - vendor
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: vendor@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /vendor/user/save-detail:
    post:
      tags:
        - vendor
      summary: store vendor detail
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                registration_certificate:
                  type: string
                  format: binary
                vat_number:
                  type: string
                  example: aaasda
                contact_number:
                  type: string
                  example: aasdas
                company_name:
                  type: string
                  example: aa2341qwer
                phone:
                  type: string
                  example: asdfasdf
                logo:
                  type: string
                  format: binary
                email:
                  type: string
                  example: asdf
                address:
                  type: string
                  example: asss
                bank:
                  type: string
                  example: aasd
                account_number:
                  type: string
                  example: asd
                cheque_photo:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/brand/brand:
    get:
      tags:
        - Brand
      summary: get all brands
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/category/category:
    get:
      tags:
        - Category
      summary: get all categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/category/category-parent:
    get:
      tags:
        - Category
      summary: get parent
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/attribute/attribute:
    get:
      tags:
        - Attribute
      summary: get all attributes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/attribute/category/id:
    get:
      tags:
        - Attribute
      summary: get category by id
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
